# Project 1: NYC Rat Sightings

## 1. Introduction & Research Question

In this project, I use an open dataset of rat sightings reported to New York City's 311 system.  
Each row represents one reported rat sighting, including when and where it happened.

My main question is:

> How many rat sightings are reported in each year, and what does the yearly trend look like?

I will:
- Load the dataset using `pandas`.
- Create a yearly count of rat sightings.
- Compute the mean, median, and mode of the yearly counts.
- Re-compute these statistics “the hard way” using only the Python standard library.
- Build a simple text-based visualization of yearly rat sightings.

## 2. Getting the Data

I downloaded the rat sightings dataset from the NYC Open Data portal and saved it as `rat_sightings.csv` in the same folder as this notebook.

Source dataset: [NYC Open Data – Rat Sightings](https://data.cityofnewyork.us/Social-Services/Rat-Sightings/3q43-55fe/about_data

In the code above, I:

- Import the `pandas` library.
- Read the CSV file into a DataFrame called `df`.
- Display the first few rows using `df.head()` to check that the data looks reasonable.

In [10]:
import pandas as pd  # Import the pandas library

# Name of the CSV file in the same folder as this notebook
data_file = "data/Rat_Sightings_20251209.csv"

# Read the CSV file into a DataFrame
df = pd.read_csv(data_file)

# Show the first few rows to confirm the data loaded correctly
df.head()

C:\Users\Yin_Z\AppData\Local\Temp\ipykernel_48100\908198572.py:7: DtypeWarning: Columns (2,17,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_file)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,67099047,2025 Dec 09 01:45:46 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,10466.0,4342 BOYD AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.896462,-73.851709,POINT (-73.85170921433942 40.89646195330815)
1,67102510,2025 Dec 09 01:35:02 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,10466.0,4357 GUNTHER AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.896878,-73.850931,POINT (-73.85093060089258 40.89687814261415)
2,67107460,2025 Dec 09 01:14:25 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,10458.0,2556 BRIGGS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.863465,-73.893753,POINT (-73.89375304851451 40.863464964877586)
3,67100800,2025 Dec 09 01:01:55 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,11225.0,49 CROWN STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.667351,-73.960229,POINT (-73.9602294900116 40.66735140693541)
4,67099042,2025 Dec 09 12:12:26 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Commercial Building,11203.0,854 CLARKSON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.656684,-73.929756,POINT (-73.92975588197113 40.656684344677615)

## 3. Exploring the Dataset with pandas

Before doing any calculations, I want to understand what is in this dataset.

- `df.shape` shows the number of rows and columns. This dataset has many thousands of rows, which is enough for this project.
- `df.columns` and `df.dtypes` show the available columns and their data types.
- I focus on two key columns:
  - `Created Date` (stored in the variable `date_column`): when the rat sighting was reported.
  - `Borough` (stored in the variable `borough_column`): which NYC borough the sighting is in.

I also checked for missing values in these columns:

- Some rows may have missing dates or boroughs.
- For the main analysis, I will drop rows where the year cannot be determined.

In the next section, I will convert the date column into a proper datetime type and create a new column called `year` to count how many rat sightings occur in each year.

In [13]:
# Check the number of rows and columns
df.shape

(278617, 38)

In [17]:
# Check the data types of each column
df.dtypes

Unique Key                          int64
Created Date                       object
Closed Date                        object
Agency                             object
Agency Name                        object
Complaint Type                     object
Descriptor                         object
Location Type                      object
Incident Zip                      float64
Incident Address                   object
Street Name                        object
Cross Street 1                     object
Cross Street 2                     object
Intersection Street 1              object
Intersection Street 2              object
Address Type                       object
City                               object
Landmark                           object
Facility Type                     float64
Status                             object
Due Date                           object
Resolution Action Updated Date     object
Community Board                    object
Borough                            object
X Coordinate (State Plane)         object
Y Coordinate (State Plane)         object
Park Facility Name                 object
Park Borough                       object
Vehicle Type                      float64
Taxi Company Borough              float64
Taxi Pick Up Location             float64
Bridge Highway Name               float64
Bridge Highway Direction          float64
Road Ramp                         float64
Bridge Highway Segment            float64
Latitude                          float64
Longitude                         float64
Location                           object
dtype: object

In [16]:
# Check the column names
df.columns

Index(['Unique Key', 'Created Date', 'Closed Date', 'Agency', 'Agency Name',
       'Complaint Type', 'Descriptor', 'Location Type', 'Incident Zip',
       'Incident Address', 'Street Name', 'Cross Street 1', 'Cross Street 2',
       'Intersection Street 1', 'Intersection Street 2', 'Address Type',
       'City', 'Landmark', 'Facility Type', 'Status', 'Due Date',
       'Resolution Action Updated Date', 'Community Board', 'Borough',
       'X Coordinate (State Plane)', 'Y Coordinate (State Plane)',
       'Park Facility Name', 'Park Borough', 'Vehicle Type',
       'Taxi Company Borough', 'Taxi Pick Up Location', 'Bridge Highway Name',
       'Bridge Highway Direction', 'Road Ramp', 'Bridge Highway Segment',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [18]:
df.describe(include="all")

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
count,2.786170e+05,278617,261993,278617,278617,278617,278617,278605,278188.000000,267684,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,276097.000000,276097.000000,276097
unique,NaN,162044,149863,1,1,1,1,54,NaN,121120,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,131399
top,NaN,2017 Feb 15 12:00:00 AM,2012 Jun 27 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,NaN,2131 WALLACE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,POINT (-73.86483898777793 40.85394627842468)
freq,NaN,179,156,278617,278617,278617,278617,118876,NaN,341,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,340
mean,4.396859e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10758.735219,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.737080,-73.935586,NaN
std,1.418604e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,580.747764,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.080203,0.065564,NaN
min,1.146439e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,83.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.499502,-74.254437,NaN
25%,3.218346e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10075.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.678178,-73.966934,NaN
50%,4.465211e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11105.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.724664,-73.940910,NaN
75%,5.645521e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11225.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.807018,-73.903008,NaN
max,6.710912e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100354.000000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.912869,-73.700772,NaN

In [ ]:
# Set the column names for date and borough
date_column = "Created Date"  # Replace with the actual date column name if different
borough_column = "Borough"  # Replace with the actual borough column name if different

# Look at the first few values of these key columns
df[[date_column, borough_column]].head()

              Created Date   Borough
0  2025 Dec 09 01:45:46 AM     BRONX
1  2025 Dec 09 01:35:02 AM     BRONX
2  2025 Dec 09 01:14:25 AM     BRONX
3  2025 Dec 09 01:01:55 AM  BROOKLYN
4  2025 Dec 09 12:12:26 AM  BROOKLYN

In [20]:
# Count missing values in the key columns
df[date_column].isna().sum(), df[borough_column].isna().sum()

(np.int64(0), np.int64(4))

In [21]:
# Quick overview of the DataFrame, including non-null counts
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278617 entries, 0 to 278616
Data columns (total 38 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   Unique Key                      278617 non-null  int64
 1   Created Date                    278617 non-null  object
 2   Closed Date                     261993 non-null  object
 3   Agency                          278617 non-null  object
 4   Agency Name                     278617 non-null  object
 5   Complaint Type                  278617 non-null  object
 6   Descriptor                      278617 non-null  object
 7   Location Type                   278605 non-null  object
 8   Incident Zip                    278188 non-null  float64
 9   Incident Address                267684 non-null  object
 10  Street Name                     267683 non-null  object
 11  Cross Street 1                  252167 non-null  object
 12  Cross Street 2                  252217 non-null  object
 13  Intersection Street 1           160271 non-null  object
 14  Intersection Street 2           160352 non-null  object
 15  Address Type                    278139 non-null  object
 16  City                            274929 non-null  object
 17  Landmark                        137773 non-null  object
 18  Facility Type                   0 non-null       float64
 19  Status                          278617 non-null  object
 20  Due Date                        132232 non-null  object
 21  Resolution Action Updated Date  270374 non-null  object
 22  Community Board                 278613 non-null  object
 23  Borough                         278613 non-null  object
 24  X Coordinate (State Plane)      276097 non-null  object
 25  Y Coordinate (State Plane)      276101 non-null  object
 26  Park Facility Name              278617 non-null  object
 27  Park Borough                    278613 non-null  object
 28  Vehicle Type                    0 non-null       float64
 29  Taxi Company Borough            0 non-null       float64
 30  Taxi Pick Up Location           0 non-null       float64
 31  Bridge Highway Name             0 non-null       float64
 32  Bridge Highway Direction        0 non-null       float64
 33  Road Ramp                       0 non-null       float64
 34  Bridge Highway Segment          0 non-null       float64
 35  Latitude                        276097 non-null  float64
 36  Longitude                       276097 non-null  float64
 37  Location                        276097 non-null  object
dtypes: float64(11), int64(1), object(26)
memory usage: 80.8+ MB

In [ ]:
# Convert the date column to datetime and extract the year
df[date_column] = pd.to_datetime(df[date_column], errors="coerce")
df["year"] = df[date_column].dt.year

# Drop rows where the year is missing
df_year = df.dropna(subset=["year"])

# Group by year and count the number of sightings in each year
yearly_counts = df_year.groupby("year").size().reset_index(name="sightings_count")

yearly_counts.head()

   year  sightings_count
0  2010            10534
1  2011            10454
2  2012            10643
3  2013            10739
4  2014            12617

## 4. Mean / Median / Mode with pandas

Now that I have a yearly summary of rat sightings, I use `pandas` to compute some basic statistics:

- **Mean**: the average number of rat sightings per year.
- **Median**: the "middle" yearly value when all years are sorted from lowest to highest.
- **Mode**: the most frequent yearly value (there can be more than one mode).

These statistics give a quick sense of what a “typical” year looks like in terms of rat activity.  
Later, I will re-compute the same values using only the Python standard library.

In [ ]:
# Convert the date column to datetime and extract the year
df[date_column] = pd.to_datetime(df[date_column], errors="coerce")
df["year"] = df[date_column].dt.year

# Drop rows where the year is missing
df_year = df.dropna(subset=["year"])

# Group by year and count the number of sightings in each year
yearly_counts = df_year.groupby("year").size().reset_index(name="sightings_count")

# Show the first few rows of the yearly summary
yearly_counts.head()

   year  sightings_count
0  2010            10534
1  2011            10454
2  2012            10643
3  2013            10739
4  2014            12617

In [24]:
# Select the numeric column we want to analyze
value_column = "sightings_count"

counts_series = yearly_counts[value_column]

# Compute summary statistics using pandas
mean_value = counts_series.mean()
median_value = counts_series.median()
mode_values = counts_series.mode()

print("Mean yearly rat sightings:", mean_value)
print("Median yearly rat sightings:", median_value)
print("Mode(s) of yearly rat sightings:", mode_values.tolist())

Mean yearly rat sightings: 17413.5625
Median yearly rat sightings: 17019.0
Mode(s) of yearly rat sightings: [10454, 10534, 10643, 10739, 12617, 15286, 16262, 16808, 17230, 17353, 19152, 19384, 25012, 25191, 25452, 26500]

## 5. Mean / Median / Mode the Hard Way (Pure Python)

For this part of the project, I re-computed the statistics using only the Python standard library:

- I used `csv.DictReader` to read the file row by row.
- I extracted the year from the date string and counted how many sightings occurred in each year.
- I implemented my own functions for the mean, median, and mode.

The results from these custom functions are very close to the ones from `pandas`.  
This is a good check that my logic is correct and that I understand what these statistics mean.

In [ ]:
import csv


def read_yearly_counts_from_csv(file_path, date_column_name):
    """
    Read the rat sightings CSV file and return a dictionary
    mapping each year to the number of sightings in that year.
    This uses only the Python standard library.
    """
    yearly_counts_dict = {}
    with open(file_path, newline="", encoding="utf-8") as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            date_str = row[date_column_name]
            if not date_str:
                # Skip rows with missing date
                continue

            # A simple way to extract the year is to take the first 4 characters,
            # assuming the date format starts with "YYYY-..."
            year_str = date_str[:4]
            if not year_str.isdigit():
                # Skip rows where the first 4 characters are not a year
                continue

            year = int(year_str)
            yearly_counts_dict[year] = yearly_counts_dict.get(year, 0) + 1

    return yearly_counts_dict


yearly_counts_dict = read_yearly_counts_from_csv(data_file, date_column)
yearly_counts_dict

{2025: 19384,
 2024: 25191,
 2023: 25452,
 2022: 26500,
 2021: 25012,
 2020: 16262,
 2019: 16808,
 2018: 17353,
 2017: 19152,
 2016: 17230,
 2015: 15286,
 2014: 12617,
 2013: 10739,
 2012: 10643,
 2011: 10454,
 2010: 10534}

In [26]:
# Extract the yearly counts as a list of numbers
numbers = list(yearly_counts_dict.values())

# Quick sanity check: show the first few values
numbers[:10]

[19384, 25191, 25452, 26500, 25012, 16262, 16808, 17353, 19152, 17230]

In [ ]:
def my_mean(values):
    """
    Compute the arithmetic mean of a list of numbers.
    """
    return sum(values) / len(values)


def my_median(values):
    """
    Compute the median of a list of numbers.
    """
    sorted_values = sorted(values)
    n = len(sorted_values)
    mid = n // 2

    if n % 2 == 1:
        # Odd number of values: return the middle one
        return sorted_values[mid]
    else:
        # Even number of values: return the average of the two middle ones
        return (sorted_values[mid - 1] + sorted_values[mid]) / 2


def my_mode(values):
    """
    Compute the mode(s) of a list of numbers.

    Returns a list because there may be more than one value
    with the highest frequency.
    """
    counts = {}
    for value in values:
        counts[value] = counts.get(value, 0) + 1

    max_count = max(counts.values())
    modes = [v for v, c in counts.items() if c == max_count]
    return modes

In [28]:
hard_mean = my_mean(numbers)
hard_median = my_median(numbers)
hard_modes = my_mode(numbers)

print("Mean yearly rat sightings (hard way):", hard_mean)
print("Median yearly rat sightings (hard way):", hard_median)
print("Mode(s) yearly rat sightings (hard way):", hard_modes)

Mean yearly rat sightings (hard way): 17413.5625
Median yearly rat sightings (hard way): 17019.0
Mode(s) yearly rat sightings (hard way): [19384, 25191, 25452, 26500, 25012, 16262, 16808, 17353, 19152, 17230, 15286, 12617, 10739, 10643, 10454, 10534]

## 6. Text-based Visualization (Pure Python)

This text-based chart shows the number of rat sightings in NYC for each year.

- Each line corresponds to a **year**.
- The number of `*` characters on each line is proportional to the number of sightings in that year.
- The chart uses a maximum width of 50 characters, so it fits comfortably on a narrow laptop screen.

Even though this is a very simple visualization, it still allows us to:

- See which years had relatively more or fewer rat sightings.
- Notice any obvious spikes or drops in the yearly counts.

In [29]:
# Sort the dictionary items by year so the chart is in order
sorted_items = sorted(yearly_counts_dict.items())

years = [item[0] for item in sorted_items]
values = [item[1] for item in sorted_items]

years[:5], values[:5]

([2010, 2011, 2012, 2013, 2014], [10534, 10454, 10643, 10739, 12617])

In [ ]:
def print_text_bar_chart(labels, values, max_width=50):
    """
    Print a simple horizontal bar chart using '*' characters.

    labels: list of labels (e.g., years)
    values: list of numeric values (e.g., counts)
    max_width: maximum number of '*' characters for the largest value
    """
    max_value = max(values)
    if max_value == 0:
        print("No data to display.")
        return

    scale = max_width / max_value

    print("Text-based Chart: Yearly Rat Sightings in NYC")
    print(
        "Each '*' represents approximately {:.1f} sightings.".format(
            max_value / max_width
        )
    )
    print()
    print("Y-axis: Year")
    print("X-axis: Number of rat sightings (represented by '*')")
    print()

    for label, value in zip(labels, values):
        bar_length = int(value * scale)
        bar = "*" * bar_length
        print(f"{label}: {bar} ({value})")

In [31]:
print_text_bar_chart(years, values)

Text-based Chart: Yearly Rat Sightings in NYC
Each '*' represents approximately 530.0 sightings.

Y-axis: Year
X-axis: Number of rat sightings (represented by '*')

2010: ******************* (10534)
2011: ******************* (10454)
2012: ******************** (10643)
2013: ******************** (10739)
2014: *********************** (12617)
2015: **************************** (15286)
2016: ******************************** (17230)
2017: ************************************ (19152)
2018: ******************************** (17353)
2019: ******************************* (16808)
2020: ****************************** (16262)
2021: *********************************************** (25012)
2022: ************************************************** (26500)
2023: ************************************************ (25452)
2024: *********************************************** (25191)
2025: ************************************ (19384)

## 7. What I Tried and Adjusted

At first, I considered analyzing rat sightings by both **borough** and **month**.  
However, this created many small groups, and the text-based chart became hard to read.

To keep the analysis simple and clear, I decided to focus on **yearly** counts:

- Yearly data is easier to summarize and visualize.
- It still answers an interesting question about the overall trend in rat activity.

This is an example of how I refined my research question as I explored the dataset.

## 8. Conclusion & Caveats

### Main takeaways

- The yearly counts of rat sightings vary over time, with some years clearly higher than others.
- The mean and median yearly counts (computed above) give a sense of what a “typical” year looks like.
- The text-based chart provides a quick visual way to compare years, even without any plotting libraries.

### Caveats

- These are **reported** rat sightings, not a full count of all rats in the city.
- Changes in public awareness, reporting behavior, or city policies could affect how many sightings get reported.
- I only looked at yearly totals. A more detailed analysis might explore differences by borough, season, or neighborhood.

Overall, this project helped me practice working with a real-world dataset,  
computing basic statistics both with `pandas` and with the Python standard library,  
and building a simple visualization using only text.